pull_request_rules:
  - name: Automatic merge on Green CI (required tests only)
    conditions:
      - check-success=build
      - label!=work-in-progress
    actions:
      merge:
        method: merge
